# Generated by Django 4.1.5 on 2023-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clase_estudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='estudiante',
            new_name='estudiantes',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='clases',
            field=models.ManyToManyField(to='api.clase'),
        ),
    ]
