# Generated by Django 4.1.5 on 2023-01-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_estudiante_clase_estudiantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='clases',
        ),
        migrations.AlterField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(related_name='tiene', to='api.estudiante'),
        ),
    ]
