# Generated by Django 4.1.5 on 2023-01-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_estudiante_clases_alter_clase_estudiantes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clase',
            table='tiene',
        ),
    ]
