# Generated by Django 4.1.5 on 2023-01-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_clase_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clase',
            table='clase',
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='estudiante',
        ),
    ]
